### ISSUE TITLE
테스트 안됨.

### ISSUE THREAD

**Issue by wonwoooochoi** [wonwoooochoi/TMHomework#2]
@gelato-recruiter 테스트 질문입니다.

1. 구동기기는 아이폰, 아이패드 모두 해야하는건지
2. 실 기기도 구동 테스트를 해야하는지
3. XCTestCase를 이용한 테스트가 가능해야하는지

답변 부탁드립니다.

**Comment by gelato-recruiter** [comment]
@wonwoooochoi 답변 드립니다.
1. 아이패드는 고려 하지 않으셔도 됩니다.
2. 기기가 없으시다면, 시뮬레이터 상에서 테스트 하셔도 됩니다.
3. 테스트 방법은 주관적으로 적합한 방식을 선택하시어 진행하시고, 그 선택 배경과 적용한 부분등을 README에 서술해 주시면 됩니다.
