### ISSUE TITLE
이미지 사이즈가 항상 640.

### ISSUE THREAD

**Issue by wonwoooochoi** [wonwoooochoi/TMHomework#4]
@gelato-recruiter
standard_resolution의 width와 height가 항상 640입니다.
이 값을 참조하는게 맞나요?

**Comment by gelato-recruiter** [comment]
@wonwoooochoi 네, 인스타그램 API의 특성입니다. 그 값이 width, height 가 다를 수 있다는 가정을 가지고 UI상의 이미지 표시 영역 사이즈를 Homework 내용을 참고하시어 가변적으로 처리해 주시면 됩니다. API로 그러한 케이스 데이터를 받기가 어려운데 어떻게 구현하고 어떻게 검증하실지도 Homework 의 내용에 포함되어 그렇습니다. 참고) standard_resolution URL 의 일부를 조정하면 원본 이미지를 얻을 수도 있고 그 원본 이미지는 가로 세로 비율이 같을 수도, 다를 수도 있습니다. 하지만, 그 경우 원본 이미지의 가로 세로 사이즈를 다운로드 받기 전에 미리 알 수 있는 방법이 없다보니, Homework의 내용에는 포함시키지 않았습니다.
